### ISSUE TITLE
SwinIR path error

### ISSUE THREAD

**Issue by iKora128** [zsyOAOA/DifFace#19]
Thank you for your great Job!!

You updated this repo in 2023/12/12 maybe, so there is no links for SwinIR model
https://github.com/zsyOAOA/DifFace/releases/download/V1.0/General_Face_ffhq512.pth

and now, I downloaded it(below link) from your release page instead of before link
https://github.com/zsyOAOA/DifFace/releases/download/V1.0/swinir_restoration512_L1.pth
but, I cant load the model for running inference.py

**Comment by zsyOAOA** [comment]
I have updated the code today. Please re-clone the repo and have a try again. @iKora128

**Comment by iKora128** [comment]
Thank you so much!! you saved my life!!
